#!/usr/bin/env zsh
# vi:ft=zsh

# Create or switch to tmux sessions without nesting a second client.
_remino_tmux_init() {
	(( $+functions[_remino_tmux_create_or_switch] )) && return

	_remino_tmux_create_or_switch() {
		local session_name=$1

		if [[ -z "$TMUX" ]]
		then
			command tmux new-session -A -s "$session_name"
			return
		fi

		if ! command tmux has-session -t "=$session_name" 2> /dev/null
		then
			command tmux new-session -d -c "$PWD" -s "$session_name" || return
		fi

		command tmux switch-client -t "=$session_name"
	}

	_remino_tmux_new_and_switch() {
		local session_name

		if [[ -z "$TMUX" ]]
		then
			command tmux new-session "$@"
			return
		fi

		session_name="$( command tmux new-session -d -P -F '#{session_name}' -c "$PWD" "$@" )" || return
		command tmux switch-client -t "=$session_name"
	}

	to() {
		if [[ -n "$1" && "${1:0:1}" != '-' ]]
		then
			_remino_tmux_create_or_switch "$1"
		else
			_remino_tmux_new_and_switch "$@"
		fi
	}

	ts() {
		if [[ -n "$1" && "${1:0:1}" != '-' ]]
		then
			_remino_tmux_new_and_switch -s "$@"
		else
			_remino_tmux_new_and_switch "$@"
		fi
	}

	_remino_tmux_directory_session() {
		local dir="${PWD##*/}"
		local md5="$( printf '%s' "$PWD" | md5sum | cut -d ' ' -f 1 )"
		local session_name="${dir}-${md5:0:6}"

		_remino_tmux_create_or_switch "$session_name"
	}

	if (( $+aliases[tds] )); then
		unalias tds
	fi
	alias tds=_remino_tmux_directory_session

	tkss() {
		local target current
		local -a kill_args

		if [[ "$1" == '-t' && -n "$2" ]]
		then
			target=$2
			kill_args=( "$@" )
		elif [[ -n "$1" && "${1:0:1}" != '-' ]]
		then
			target=$1
			kill_args=( -t "$target" )
		else
			target="$( command tmux display-message -p '#{session_name}' 2> /dev/null )"
			kill_args=( "$@" )
		fi

		if [[ -n "$TMUX" && -n "$target" ]]
		then
			current="$( command tmux display-message -p '#{session_name}' 2> /dev/null )"
			if [[ "$target" == "$current" ]]
			then
				command tmux switch-client -l 2> /dev/null
			fi
		fi

		command tmux kill-session "${kill_args[@]}"
	}

}
